project:
  type: website
  output-dir: docs
  
website: 
  title: "Foundation Math Learning"
  navbar:
    left:
      - href: https://yuuuulu.github.io/
        text: yuuuulu
      - href: index.qmd
        text: Homepage
      - href: aph101.html
        text: Biostat and R
      - href: mth107.html
        text: Advanced Linear Algebra
      - href: Simple_ODEs.html
        text: ODEs and PDEs with codes
      - href: mth106.html
        text: ODE, PDE, and Fourier Series
      
      - href: Mathematical Analysis 1.qmd
        text: Analysis 1
      - href: mth1113.html
        text: intro to prob, and stat.
      #- href: eng pde.qmd
        #text: PDE  
      - href: Calculus.html
        text: Calculus

      
      #- href: sequence.qmd
       # text: sequence
      #- href: Lagrange.qmd
       # text: lasso and Lagrange method
      #- href: understand directional derivative deeply.qmd
        #text: Directional Derivative
      
format: 
  html: 
    theme: cosmo
    toc: true