project:
  type: website
  output-dir: docs
  
website: 
  title: "Foundation Math Learning"
  navbar:
    left:
      - href: https://yuuuulu.github.io/
        text: yuuuulu
      - href: index.qmd
        text: Homepage
      - href: mth107.qmd
        text: Advanced Linear Algebra
      - href: Mathematical Analysis 1.qmd
        text: Analysis 1
      - href: mth1113.qmd
        text: intro to prob, and stat.
      - href: eng pde.qmd
        text: PDE 
      - href: Calculus.qmd
        text: Calculus
      #- href: sequence.qmd
       # text: sequence
      #- href: Lagrange.qmd
       # text: lasso and Lagrange method
      #- href: understand directional derivative deeply.qmd
        #text: Directional Derivative
      
format: 
  html: 
    theme: cosmo
    toc: true