---
title: "(sequence)sinx/x's 0-infinite's integral"
format: html
editor: visual
---

Dr.Fajin Wei teach me how to do it. He is very good at Calculus and Modeling. He is kind to help our students. Thanks to him very much!

# integral problems with solution of alternating integral test



question: does $$\int_{0}^{\infty}sinx/x\,dx$$ converge?

It is easy to think of these 2 famous but difficultly proved formula:
$$\int_{-\infty}^{\infty}sinx/x\,dx=\pi
$$
$$\int_{-\infty}^{\infty}e^{-x^2}\,dx=\pi
$$
However, they are not useful, which is how charasmatic the math is! I love math!


$$=\Sigma_{n=1}^{\infty}\int_{2(n-1)\pi}^{2n\pi}sinx/x\,dx
$$
Then we let $x-[2(n-1)\pi]=y$(dx=dy)

so $$=\Sigma_{n=1}^{\infty}\int_{0}^{2\pi}siny/(y+[2(n-1)\pi])\,dy$$
=$$=\Sigma_{n=1}^{\infty}\int_{0}^{\pi}siny/(y+[2(n-1)\pi])\,dy+\Sigma_{n=1}^{\infty}\int_{\pi}^{2\pi}siny/(y+[2(n-1)\pi])\,dy$$


Then we let y-$\pi$=z(dy=dz)


$$=\Sigma_{n=1}^{\infty}\int_{0}^{\pi}siny/(y+[2(n-1)\pi])\,dy+\Sigma_{n=1}^{\infty}\int_{0}^{\pi}-sinz/(z+[(2n-1)\pi])\,dz$$
$$=\Sigma_{n=1}^{\infty}\int_{0}^{\pi}sinm/(m+[2(n-1)\pi])\,dm+\Sigma_{n=1}^{\infty}\int_{0}^{\pi}-sinm/(m+[(2n-1)\pi])\,dm$$


so if $$a_n=\int_{0}^{\pi}sinm/(m+(n-1)\pi)$$
$$\int_{0}^{\infty}sinx/x\,dx=a_1-a_2+a_3-a_4+...+a_n$$, which is an alternating series!

Coincidently, it is decresing and $a_n<\int_{0}^{\pi}1/(n-1)\pi\,dm=1/(n-1)$, and $\lim_{{n \to \infty}} \left( \frac{1}{n-1}  \right) = 0$ so $\lim_{{n \to \infty}}a_n=0$
So it converges(Alternating series test).


# similar question 2
Thanks for Dr.Chi-Kun Lin to teach me this kind of problems! 

$$
\int_0^\infty \frac{1}{1 + x^p \sin^2 x} \, dx
$$








a. 

$$
\sum_{n=0}^\infty \int_0^{\frac{\pi}{2}} \frac{1}{1 + \left( n + \frac{1}{2} \right)^2 p \sin^2 t} \, dt = \int_0^{\frac{\pi}{2}} \frac{1}{1 + \left( n + \frac{1}{2} \right)^2 p \sin^2 t} \, dt
$$


$$\Sigma\int_0^{\frac{\pi}{2}} \frac{1}{1 + \left( n\pi/2 + t \right)^ p \sin^2 t} \, dt + \int_0^{\frac{\pi}{2}} \frac{1}{1 + \left(( n + 1 \right)\pi/2-t)^ p sin^2t} \, dt$$

for:

$$
x_n = \Sigma\int_0^{\frac{\pi}{2}} \frac{1}{1 + \left( n\pi/2 + t \right)^ p \sin^2 t} \, dt + \int_0^{\frac{\pi}{2}} \frac{1}{1 + \left(( n + 1 \right)\pi/2-t)^ p sin^2t} \, dt,
$$

there has

$$2 \int_0^{\frac{\pi}{2}} \frac{1}{1 + \left( (n + 1) \frac{\pi}{2} \right)^ p t^2} \, dt \leq x_n \leq 2 \int_0^{\frac{\pi}{2}} \frac{1}{1 + \left( (n + 1) \frac{\pi}{2} \right) ^p \frac{4}{\pi^2} t^2} \, dt$$






c. However, the integrals on both sides of the inequality can be calculated separately. For example:

$$
\int_0^1 \frac{1}{1 + \left( (n + 1) \frac{\pi}{2} \right)^ p t^2} \, dt = \frac{1}{\sqrt{((n + 1) \frac{\pi}{2} )^p}} \arctan \left( \sqrt{(n + 1) \frac{\pi}{2}}^{2p}\pi/2 \right) \geq \frac{1}{\sqrt{(n + 1) \frac{\pi}{2} }^{2p}  } \frac{\pi}{4}
$$



